title: Sense HAT Pong
hero_image: images/banner.png
description: Make a single-player Pong game using your Raspberry Pi and Sense HAT
original_url: https://raspberrypi.org/learning/sense-hat-pong
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-1, manufacture-0, community-0
interests: games
technologies: python, sense-hat
site_areas: projects
hardware: sense-hat
software: python
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Connect to the Sense HAT
- title: Light up an LED
- title: Make a bat
- title: Move the bat
- title: Create a ball
- title: Move the ball
- title: Collision with the bat
- title: You lose
- title: "Challenge: add more features"