---
title: Sense Hat पोंग
hero_image: images/banner.png
description: अपने Raspberry Pi और Sense HAT का उपयोग करके एक एकल-खिलाड़ी पोंग गेम बनाएं
original_url: https://raspberrypi.org/learning/sense-hat-pong
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-1, manufacture-0, community-0
interests: games
technologies: python, sense-hat
site_areas: projects
hardware: sense-hat
software: python
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: परिचय
  - 
    title: आपको किसकी ज़रूरत होगी
  - 
    title: Sense HAT से कनेक्ट करें
  - 
    title: LED को जलाना
    completion:
      - engaged
  - 
    title: एक बल्ला बनाए
  - 
    title: बल्ला घुमाएं
  - 
    title: एक गेंद बनाएँ
  - 
    title: गेंद को हिलाएं
  - 
    title: बल्ले से टकराव
  - 
    title: तुम हारे
    completion:
      - internal
  - 
    title: 'चुनौती: अधिक विशेषताएं जोड़ें'
